# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "bb3d7694aa9a53e849de71dc2f2806fa"
name = "RestockPing: Back in Stock"
application_url = "https://restockping.vercel.app"
embedded = true
handle = "restockping-back-in-stock"

[build]
automatically_update_urls_on_dev = true
dev_store_url = ""

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  uri = "/webhooks"
  topics = [ "app/uninstalled", "inventory_levels/update" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_inventory,read_products,read_themes,write_inventory,write_products"

[auth]
redirect_urls = [
  "https://restockping.vercel.app/auth/callback",
  "https://restockping.vercel.app/auth/shopify/callback",
  "https://restockping.vercel.app/api/auth/callback"
]

[app_proxy]
url = "https://restockping.vercel.app/apps/restockping"
subpath = "restockping"
prefix = "apps"

[pos]
embedded = false
